name: bookmaek
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  font_awesome_flutter: ^8.4.0
  http: ^0.12.0+2
  image_picker: ^0.6.0+8
  flutter_inappbrowser: ^1.2.1
  curved_navigation_bar: ^0.2.20
  shared_preferences: ^0.5.3+4
  animated_splash: ^1.0.0
  # camera: ^0.5.2+1
  # firebase_core: ^0.4.0+3
  # firebase_auth: ^0.11.1+5
  # cloud_firestore: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/grey.jpeg
   - assets/images/test-day.jpg
   - assets/images/test-night.jpg
   - assets/images/ale.jpg
   - assets/images/landing-bg.jpg
   - assets/images/login-bg.jpg
   - assets/images/signup-bg.jpg
   - assets/images/night.jpg
   - assets/images/sky.jpg
   - assets/images/test.jpg
   - assets/images/1.jpg
   - assets/images/2.jpg
   - assets/images/3.jpg
   - assets/images/4.jpg
   - assets/images/5.jpg
   - assets/images/6.jpg
   - assets/images/7.jpg
   - assets/images/8.jpg
   - assets/images/9.jpg
   - assets/images/10.jpg
   - assets/images/11.jpg
   - assets/images/12.jpg
   - assets/images/13.jpg
   - assets/images/14.jpg
   - assets/images/15.jpg
   - assets/images/16.jpg
   - assets/images/17.jpg
   - assets/images/18.jpg
   - assets/images/19.jpg
   - assets/images/20.jpg
   - assets/images/21.jpg
   - assets/images/22.jpg
   - assets/images/23.jpg
   - assets/images/24.jpg
   - assets/images/25.jpg
   - assets/images/26.jpg
   - assets/images/27.jpg
   - assets/images/28.jpg
   - assets/images/29.jpg
   - assets/images/30.jpg
   - assets/images/31.jpg
   - assets/images/32.jpg
   - assets/images/33.jpg
   - assets/images/34.jpg
   - assets/images/35.jpg
   - assets/images/36.jpg
   - assets/images/37.jpg
   - assets/images/38.jpg
   - assets/images/39.jpg
   - assets/images/40.jpg
   - assets/images/41.jpg
   - assets/images/42.jpg
   - assets/images/43.jpg
   - assets/images/44.jpg
   - assets/images/45.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
